### ISSUE TITLE
BenBot is stuck in my channel

### ISSUE THREAD

**Issue by NCommander** [benbaptist/benbot#30]
When I originally setup benbot in my channel, I got an internal server error. I repeated the process and ended up w/ "announcer" and "benbot" in my channel. I had announcer leave, but benbot remains stuck; can you see what happened in the database?

**Comment by benbaptist** [comment]
Ah, certainly - my apologies for not responding immediately. Wi investigate and fix once I get  back to the office in a couple hours or so.

**Comment by benbaptist** [comment]
I'm not certain what you want me to do - do you want me to get the bot removed, or is the bot not functioning properly, etc.?

[edited for clarity]

**Comment by NCommander** [comment]
At least I'd like control of them. I can control announcer and get it to leave and join on command but the actual "benbot" account is (or at least was) stupid with no admin UI for it.

**Comment by benbaptist** [comment]
Looking into the error logs, it seems that you were being affected by #31 (which is now fixed) and another issue with the "Add Channel" page being screwed up. This is because I switched everything to using IDs in version 3.3 and broke some stuff - mostly because I regrettably rushed that update out way too quickly.

Going to fix the addchannel page right now, and hopefully it'll all be good.

**Comment by benbaptist** [comment]
I presume this is resolved, so I will close this now. Feel free to re-open if it's not.
